### ISSUE TITLE
Bun in GitHub Actions does get stuck on stitching stage

### ISSUE THREAD

**Issue by OmarKhled** [remotion-dev/remotion#3219]
# Render Media stuck at certain point

I've a lil remotion project that creates simple videos that has text captions on a background video. Very simple logic, nothing complex. I have a github action pipeline to render this project using renderMedia, when invoked, the video starts to render and progresses normally till it reaches a certain point (I enabled verbose logging and it was mostly 92% or 72/73% don't know why these numbers 😅). 

Sometimes, the pipeline passes successfully and nothing gets wrong but this is like a 5% chance.

**Rendering with renderMedia works fine on my local machine.**

I'm using bun if that can cause an issue.

I saw on the bun support page that bun sometimes doesn't quit render automatically, and tried to verify that this is not my case, by checking if there is an output file in the out directory evey time onProgress is called, and couldn't find that an output file is emitted (at least until it gets stuck).

Remotion Version: 4.0.74
Runs on github actions ubuntu-latest.

**Comment by OmarKhled** [comment]
Here is the github worflow file if it helps 

```
name: Render Video
on:
  workflow_dispatch:
    inputs:
      ....
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Emit input props
        run: echo $WORKFLOW_INPUT | tee input-props.json | jq -C '.'
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}

      - name: Bun Dependencies Install
        run: bun i
      - name: Python Dependencies Install
        run: pip install g4f
      - name: Emit Enviroment Variables
        run: touch .env &&
          ......
      - name: Install FFMPEG
        run: sudo apt install ffmpeg
      - name: Fetching latest chrome version
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - name: Installing Chrome
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb
      - name: Rendering Video
        run: bun ./pipe
```
You can see above that I tried to install the latest chrome version (hoped that this would fix the issue but it doesn't :")
