### ISSUE TITLE
`Failed to launch the browser process!` in docker container

### ISSUE THREAD

**Issue by greffgreff** [remotion-dev/remotion#3808]
Hi. I'm currently self-hosting my personal computer as a Github runner for a private repository of mine to render videos at a lower cost but I am getting the following error:
```
/home/docker/actions-runner/_work/renderer-api/renderer-api/node_modules/@remotion/renderer/dist/browser/BrowserRunner.js:255
            reject(new Error([
                   ^
Error: Failed to launch the browser process!
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/home/docker/actions-runner/_work/renderer-api/renderer-api/node_modules/@remotion/renderer/dist/browser/BrowserRunner.js:255:20)
    at ChildProcess.<anonymous> (/home/docker/actions-runner/_work/renderer-api/renderer-api/node_modules/@remotion/renderer/dist/browser/BrowserRunner.js:246:24)
    at ChildProcess.emit (node:events:530:35)
    at ChildProcess._handle.onexit (node:internal/child_process:2[9](https://github.com/greffgreff/renderer-api/actions/runs/8881586278/job/24384296236#step:7:10)4:12)
```
While I would have attempted to troubleshoot a bit longer, I couldn't find a way to increase verbose to get a more precise error. 

The github action that I am running looks very similar to [that of remotion](https://github.com/remotion-dev/template-helloworld/blob/main/.github/workflows/render-video.yml):
```yml
name: Render video
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  render:
    name: Render video
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt-get update -y
      - run: sudo apt-get install ffmpeg -y
      - run: npm i
      - run: npm run render
      - uses: actions/upload-artifact@v4
        with:
          name: out.mp4
          path: out/video.mp4
```

And if that helps, here is the Dockerfile that I am using as self-hosted runner for the github actions:
```Dockerfile
FROM ubuntu:latest

ARG RUNNER_VERSION="2.316.0"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update -y \
    && apt upgrade -y
    
RUN apt-get -y install sudo curl jq npm \
    && apt-get clean

RUN curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - \
    && apt-get install -y nodejs

RUN adduser --disabled-password --gecos '' docker \
    && adduser docker sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN cd /home/docker && mkdir actions-runner && cd actions-runner \
    && curl -O -L https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz \
    && tar xzf ./actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz

RUN chown -R docker ~docker && /home/docker/actions-runner/bin/installdependencies.sh

COPY start.sh start.sh

# make the script executable
RUN chmod +x start.sh

# since the config and run script for actions are not allowed to be run by root,
# set the user to "docker" so all subsequent commands are run as the docker user
USER docker

ENTRYPOINT ["./start.sh"]
```

**Comment by greffgreff** [comment]
@JonnyBurger I am getting the following error:
```
$ sudo npx remotion browser ensure
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-29T20_19_22_526Z-debug-0.log
```
And the logs are:
```
$ sudo cat /root/.npm/_logs/2024-04-29T20_19_22_526Z-debug-0.log
0 verbose cli /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.5.0
2 info using node@v20.12.2
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 10ms
18 timing config:load:flatten Completed in 4ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm exec remotion browser ensure
22 verbose argv "exec" "--" "remotion" "browser" "ensure"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-04-29T20_19_22_526Z-
26 verbose logfile /root/.npm/_logs/2024-04-29T20_19_22_526Z-debug-0.log
27 timing npm:load:logFile Completed in 13ms
28 timing npm:load:timers Completed in 1ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 59ms
31 silly logfile done cleaning log files
32 timing arborist:ctor Completed in 1ms
33 http fetch GET 200 https://registry.npmjs.org/remotion 300ms (cache miss)
34 timing command:exec Completed in 342ms
35 verbose stack Error: could not determine executable to run
35 verbose stack     at getBinFromManifest (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
35 verbose stack     at exec (/usr/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:15)
35 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli-entry.js:61:5)
36 verbose pkgid remotion@4.0.148
37 verbose cwd /
38 verbose Linux 5.15.146.1-microsoft-standard-WSL2
39 verbose node v20.12.2
40 verbose npm  v10.5.0
41 error could not determine executable to run
42 verbose exit 1
43 timing npm Completed in 631ms
44 verbose code 1
```

**Comment by greffgreff** [comment]
So i updated the workflow file to include `--log=verbose` and added `npx remotion browser ensure` before rendering but the error persists:
```yml
name: Render video
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  render:
    name: Render video
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt-get update -y
      - run: sudo apt-get install ffmpeg -y 
      - run: npm i
      - run: npx remotion browser ensure
      - run: npm run render --log=verbose
      - uses: actions/upload-artifact@v4
        with:
          name: out.mp4
          path: out/video.mp4
```
