### ISSUE TITLE
Timeline Viewer: Global CSS affects timeline UI

### ISSUE THREAD

**Issue by marcusstenbeck** [remotion-dev/remotion#604]
# Bug Report 🐛

There are certain parts of the UI that are affected when setting global CSS rules on `html` and `body`.

In my particular use-case I'm setting a larger-than normal base font size since it simplifies working with TailwindCSS and `rem` units in general. Video dimensions are rather large so a base font size should be larger than "normal" in web dev.

I've attached an image and a CSS file that will reproduce the error.

```css
/* import this CSS into the default template's Video.tsx */

html {
  font-size: 64px;
}
```

As you can see the preview size dropdown is way too large.

![image](https://user-images.githubusercontent.com/616906/134763816-bd26ccf6-a483-42e0-bbed-3f9f8f5d0264.png)
